In [1]:
# 导入模块
import os
import gc
import pandas as pd
from matplotlib import pyplot as plt
%matplotlib inline

In [3]:
# 指定数据集文件
DATA_SET_PATH = "/root/mounted/datasets/data_0515/"
KN_CSV = os.path.join(DATA_SET_PATH, "knowledge.csv")
TRAIN_CSV = os.path.join(DATA_SET_PATH, "train.csv")
TEST_CSV = os.path.join(DATA_SET_PATH, "test.csv")
SUBMIT_CSV = os.path.join(DATA_SET_PATH, "submit.csv")
CHAR_EMBED_PKL = os.path.join(DATA_SET_PATH, "char_embed.pkl")
WORD_EMBED_PKL = os.path.join(DATA_SET_PATH, "word_embed.pkl")
QUESTION_PKL = os.path.join(DATA_SET_PATH, "question.pkl")
INTERMEDIATE_DATA_PATH = os.path.join(DATA_SET_PATH, 'intermediate')
KN_TRAIN_CSV = os.path.join(INTERMEDIATE_DATA_PATH, 'kn_train.csv')

In [4]:
kn_train_csv = pd.read_csv(KN_TRAIN_CSV)
kn_train_csv

           qid_x    qid_y  label
0        Q131177  Q112611      1
1        Q131177  Q316380      0
2        Q131177  Q142969      0
3        Q131177  Q610021      0
4        Q131177  Q586666      0
5        Q131177  Q487343      0
6        Q131177  Q129344      0
7        Q131177  Q558472      0
8        Q131177  Q434835      0
9        Q131177  Q082082      0
10       Q131177  Q613217      1
11       Q131177  Q330210      0
12       Q131177  Q094803      0
13       Q131177  Q410441      0
14       Q131177  Q234555      1
15       Q131177  Q571153      0
16       Q131177  Q662731      1
17       Q131177  Q018140      0
18       Q131177  Q534275      0
19       Q131177  Q285832      0
20       Q131177  Q407872      0
21       Q131177  Q702506      1
22       Q131177  Q536500      1
23       Q131177  Q262388      0
24       Q131177  Q545358      0
25       Q131177  Q255286      0
26       Q131177  Q663316      0
27       Q131177  Q318965      0
28       Q131177  Q108090      0
29       Q131177  Q354153      0
...          ...      ...    ...
4049410  Q366183  Q397900      0
4049411  Q366183  Q473294      0
4049412  Q366183  Q670928      0
4049413  Q366183  Q075735      0
4049414  Q366183  Q373684      0
4049415  Q366183  Q393072      0
4049416  Q366183  Q642852      0
4049417  Q366183  Q200442      0
4049418  Q366183  Q640243      0
4049419  Q366183  Q500505      0
4049420  Q366183  Q255473      0
4049421  Q366183  Q653463      0
4049422  Q366183  Q650488      0
4049423  Q366183  Q343913      0
4049424  Q127357  Q472682      0
4049425  Q127357  Q335354      0
4049426  Q127357  Q397900      0
4049427  Q127357  Q473294      0
4049428  Q127357  Q670928      0
4049429  Q127357  Q075735      0
4049430  Q127357  Q373684      0
4049431  Q127357  Q393072      0
4049432  Q127357  Q642852      0
4049433  Q127357  Q200442      0
4049434  Q127357  Q640243      0
4049435  Q127357  Q500505      0
4049436  Q127357  Q255473      0
4049437  Q127357  Q653463      0
4049438  Q127357  Q650488      0
4049439  Q127357  Q343913      0

[4049440 rows x 3 columns]